# Generated by Django 6.0.5 on 2026-07-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUsers',
        ),
    ]
