# Generated by Django 6.0.5 on 2026-07-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='data',
            new_name='date',
        ),
    ]
