# Generated by Django 6.0.5 on 2026-07-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_rename_data_diary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(),
        ),
    ]
