# Generated by Django 6.0.5 on 2026-07-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_diary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='page_type',
            field=models.CharField(default='page1', max_length=20),
        ),
    ]
